# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='auctionobject',
            name='bidAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionobject',
            name='minAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctionobject',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctionsite.Bidder'),
        ),
    ]
